### PR TITLE
Remove RBDigital Integration

### PR DESCRIPTION
**Pull request by jonathangreen**
Remove RBDigital integration because all their collections have been moved over to Overdrive.

### CODE REVIEW

**Review by vbessonov — APPROVED** [review]
It looks okay. I just have a question regarding the migration: should we remove all the RBDigital content or reassign it to Overdrive?

**Comment by tdilauro** [comment]
> It looks okay. I just have a question regarding the migration: should we remove all the RBDigital content or reassign it to Overdrive?

@vbessonov It will have different identifiers and likely other details in OverDrive.

**Review by tdilauro — COMMENTED** [review]
The RBdigital stuff looks good.

Can you say more about the Feedbooks-related changes in some of the files?

**Comment by jonathangreen** [comment]
The changes in: 
- test_collection.py 
- test_patron.py
- test_credential.py

Were all more generic tests that were using `DataSource.RB_DIGITAL` in the setup for the tests. In these cases, since `DataSource.RB_DIGITAL` no longer exists, I replaced this with DataSource.FEEDBOOKS. It really could have been any data source other then RB Digital.

**Review by tdilauro — APPROVED** [review]
Got it! All good, then.

**Pull request merged**
