### PR TITLE
Update package name for webpub-manifest-parser

### PR DESCRIPTION
**Pull request by jonathangreen**
Use the new Palace repo for `webpub-manifest-parser` located here:
https://github.com/ThePalaceProject/webpub-manifest-parser

### CODE REVIEW

**Review by tdilauro — APPROVED** [review]

**Review by vbessonov — APPROVED** [review]

**Comment by vbessonov** [comment]
@jonathangreen, @tdilauro, I approved the PR but later realised that it's better not to merge this PR. `palace-webpub-manifest-parser` is not compatible with the older version of `webpub-manifest-parser` and `opds2_import` will not work as expected. I'll update the `requirements-base.txt` in my PR.

**Comment by jonathangreen** [comment]
@vbessonov I'm pulling in v1.0.0 of `palace-webpub-manifest-parser`, which is a version I just tagged. Is this version not compatible? I thought this was basically the same code as in the NYPL repo.

**Comment by tdilauro** [comment]
@vbessonov Oh, right. I forgot about that. It's the reason the reason that the change would have broken NYPL's builds, right?

**Comment by jonathangreen** [comment]
Looking though the NYPL code, is it [this PR](https://github.com/NYPL-Simplified/python-webpub-manifest-parser/pull/2) that hasn't been released on PyPI yet that had the API changes that would cause problems? 


I didn't realize that what is in `master` on the NYPL repo isn't actually what we are running, I thought it was the new code in https://github.com/ThePalaceProject/webpub-manifest-parser/pull/2 that would be incompatible.

**Pull request closed without merging**
